config:
  web_name: http://www.localhost.pl
  host: http://localhost:3000
  
mailer:
  adress: smtp.gmail.com
  port: 587
  domain: gmail.com
  user_name: urbanczykd@gmail.com
  password: xxx
  authentication: plain
  enable_starttls_auto: true
  
  
