--- !map:ActiveSupport::HashWithIndifferentAccess 
config: !map:ActiveSupport::HashWithIndifferentAccess 
  web_name: http://www.localhost.pl
  host: http://localhost:3000
mailer: !map:ActiveSupport::HashWithIndifferentAccess 
  adress: smtp.gmail.com
  port: "587"
  domain: gmail.com
  user_name: urbanczykd@gmail.com
  password: xxxx
  authentication: plain
contact: !map:ActiveSupport::HashWithIndifferentAccess 
  adress: smtp.gmail.com
  port: "587"
  domain: gmail.com
  user_name: urbanczykd@gmail.com
  password: xxxx
  sendto: urbanczykd@gmail.com
